### ISSUE TITLE
【提议】是否会为 自动群名片 功能加入开关

### ISSUE THREAD

**Issue by yuan488** [Nwflower/flower-plugin#2]
是否会为 自动群名片 功能加入开关，或自定义更改频率，频繁更换群名片可能更容易导致账号被风控冻结

**Comment by Nwflower** [comment]
2小时内更新你说的功能。
此外，“更容易导致账号被风控冻结”没有依据。该操作已经过7*24小时、多达98个群的持续性测试而未触发风控。
