### ISSUE TITLE
关于群名片的内存设置的配置文件没有默认生成

### ISSUE THREAD

**Issue by ZYFDroid** [Nwflower/flower-plugin#4]
运行插件后插件的配置目录下没有生成关于群名片内存占用的配置文件，也没有找到此配置的默认配置文件，希望能添加上去

**Comment by Nwflower** [comment]
你好，该功能已更新。
更新至最新版后运行，配置文件将在插件目录/config/group.name.yaml处生成。请根据注释修改该配置文件。
