### ISSUE TITLE
[功能建议]单群抽卡次数配置

### ISSUE THREAD

**Issue by wanting0521** [Nwflower/flower-plugin#9]
考虑新增单群的次数配置文件或者配置功能么

**Comment by Nwflower** [comment]
一直都有这个功能 请在你要配置的群聊发送 #设置抽卡

**Comment by Nwflower** [comment]
建议下次读完README后再来提问

**Comment by wanting0521** [comment]
可能我意思没表达清楚，我意思是可后台直接读写的配置文件或者锅巴配置之类的批量修改的方式，因为群比较多单个改比较麻烦，但还是感谢您能回复我。

**Comment by Nwflower** [comment]
配置文件flower-plugin\GachaMOD\Genshin\config\coin.yaml
格式参照已有数据或者如下
群号：
blue:蓝球数
pink:粉球数

**Comment by wanting0521** [comment]
好的，感谢
